version: '3'

networks:
  om3-network:
    driver: bridge

services:
  be-orkes-conductor:
    container_name: be-orkes-conductor
    build:
      context: .
      dockerfile: ./Dockerfile
    image: phidinh:be-orkes-conductor:latest
    ports:
      - '5000:5000'
    working_dir: /app
    volumes:
      - ./:/app
    command: ['npm', 'run', 'start:dev']
    networks:
      - om3-network
    env_file:
      - ./.env
